languageCode = "zh-cn"
languageName = "Simplified Chinese (China)"
weight = 1
title = "Ruize Sun の Blog"

[params]
  displayName = "简体中文"
  isoCode = "cn"
  dateFormat = "2006 January 2"
  logo = "img/site_logo.png"
  description = "HeTongRe4per's website"

[author]
  name = "Ruize Sun"
  image = "img/avatar.png"
  headline = "."
  bio = "."
  links = [
    { github = "https://www.github.com/ruizesun/" },
   ]
